modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    description = '''${mod_description}'''
    authors = "${mod_author}"
    logoFile = "icon.png"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    mandatory = true
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    side = "CLIENT"

[[dependencies.${mod_id}]]
    modId = "emi"
    versionRange = "[${emi_version},)"
    mandatory = true
    side = "CLIENT"